---
- hosts: all
  become_user: root
  serial: 2

  tasks:

    # this task will upgrade/install the rpm's if application is stopped
    - name: upgrade all packages on the server
      yum:
       name=*
       state=latest

